=>[q0]-eps->[q0]
[q0]-init->[q0]
[q1]-init->[q1]
[q2]-init->[q2]
(q3)-init->(q3)
[q0]-java~lang~Object~init->[q0]
[q1]-java~lang~Object~init->[q1]
[q2]-java~lang~Object~init->[q2]
(q3)-java~lang~Object~init->(q3)
[q0]-even->[q1]
[q1]-eps->[q1]
[q1]-even->(q3)
(q3)-even->(q3)
(q3)-odd->(q3)
(q3)-eps->(q3)
[q1]-odd->[q2]
[q0]-odd->[q2]
[q2]-odd->(q3)
[q2]-eps->[q2]
[q2]-even->[q1]
